steps:
  # Step 1: Access Secret from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'access-secret'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="streamlit-secrets" > streamlit-secrets.txt

# Step 2: Build Docker Image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--file=Dockerfile'
    - '--no-cache'
    - '--platform=linux/amd64'
    - '--build-arg'
    - 'STREAMLIT_SECRETS2=$STREAMLIT_SECRETS2'
    - '--build-arg'
    - 'STREAMLIT_SECRETS=$(cat streamlit-secrets.txt)'
    - '-t'
    - 'gcr.io/$PROJECT_ID/cl-data-dashboard:$COMMIT_SHA'
    - '.'
  secretEnv: ['STREAMLIT_SECRETS,STREAMLIT_SECRETS2']  
images:
  - 'gcr.io/$PROJECT_ID/cl-data-dashboard:$COMMIT_SHA'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/streamlit-secrets/versions/latest
    env: 'STREAMLIT_SECRETS2'

#serviceAccount: projects/$PROJECT_ID/serviceAccounts/streamlit-data-dash@dataexploration-193817.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY

