steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "PROJECT_ID: $PROJECT_ID"
      echo "COMMIT_SHA: $COMMIT_SHA"
      
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '--file=Dockerfile'
    - '--no-cache'
    - '--platform=linux/amd64'
    - '-t'
    - 'gcr.io/$PROJECT_ID/cl-data-dashboard:$COMMIT_SHA'
    - '.'
  secretEnv: ['STREAMLIT_SECRETS']  
images:
  - 'gcr.io/$PROJECT_ID/cl-data-dashboard:$COMMIT_SHA'

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/streamlit-secrets/versions/latest
    env: 'STREAMLIT_SECRETS'

serviceAccount: projects/$PROJECT_ID/serviceAccounts/405806232197-compute@developer.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY

