steps:
  # Step to retrieve the service account key from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo $KEYFILE_CONTENT > keyfile.json

    secretEnv: ['KEYFILE_CONTENT']

  # Step to access and write other secrets to a file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --project=dataexploration-193817 --secret=streamlit-secrets > .streamlit/secrets.toml

  # Build the Docker image, including the secrets in the context
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--platform'
      - 'linux/amd64'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cl-data-dashboard:$COMMIT_SHA'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/cl-data-dashboard:$COMMIT_SHA'

secrets:
- kmsKeyName: projects/$PROJECT_ID/locations/global/keyRings/KEY_RING/cryptoKeys/KEY_NAME
  secretEnv:
    KEYFILE_CONTENT: 'projects/$PROJECT_ID/secrets/my-service-account-key/versions/latest'
