steps:
  # Step 1: Access Secret from Secret Manager
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'access-secret'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud secrets versions access latest --secret="streamlit-secrets"


# Step 3: Build Docker Image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--file=Dockerfile'
      - '--no-cache'
      - '--platform=linux/amd64'
      - '--build-arg'
      - 'STREAMLIT_SECRETS'
      - '.'


serviceAccount: projects/$PROJECT_ID/serviceAccounts/streamlit-data-dash@dataexploration-193817.iam.gserviceaccount.com
options:
  logging: CLOUD_LOGGING_ONLY

