steps:
  # Step to download keyfile.json from Cloud Storage to /workspace
  - name: 'gcr.io/cloud-builders/gsutil'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gsutil cp gs://cloudbuild-1/servicekey.json /workspace/keyfile.json
    id: 'download-keyfile'

  # Continue with your existing build steps
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--no-cache'
      - '--platform'
      - 'linux/amd64'
      - '--build-arg'
      - 'KEYFILE_PATH=/workspace/keyfile.json'
      - '-t'
      - 'gcr.io/$PROJECT_ID/cl-data-dashboard:$COMMIT_SHA'
      - '.'
    waitFor:
      - 'download-keyfile'

images:
  - 'gcr.io/$PROJECT_ID/cl-data-dashboard:$COMMIT_SHA'

secrets:
  - kmsKeyName: projects/$PROJECT_ID/locations/global/keyRings/$KEY_RING/cryptoKeys/$KEY_NAME
    secretEnv:
      KEYFILE_CONTENT: 'projects/$PROJECT_ID/secrets/my-service-account-key/versions/latest'
