##[theme2]
#primaryColor="#ffa952"
#backgroundColor="#feffdf"
#secondaryBackgroundColor="#dde0ab"
#textColor="#347474"

[theme]
primaryColor="#ffa952"
backgroundColor="#feffdf"
secondaryBackgroundColor="#ffe79a"
textColor="#394a51" 